server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:/tmp/multiplication;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
amqp:
  exchange:
    attempts: attempts.topic
logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG
service:
  gamification:
    host: http://localhost:8081
